# ####################################### #
# 此文件是本項目的主配置文件，所有配置將被應用 #
# ####################################### #

# Spring的配置
spring:
  # Profile的配置
  profiles:
    # 激活哪些Profile配置
    active: dev


# MyBatis Plus配置
mybatis-plus:
  # 配置SQL語句的XML文件的位置
  mapper-locations: classpath:mappers/**/*.xml

# Knife4j配置
knife4j:
  # 開啓增強模式
  enable: true
